---
Name: 'default'
---
Database:
  host: 'default'
  name: 'default'
Email:
  admin_email: ''
SSViewer:
  theme: 'default'
LeftAndMain:
  help_link: 'http://silverstripe.bigfork.co.uk/v3/'
SiteConfig:
  extensions:
    - SiteConfigExtension
Page:
  extensions:
    - ShareCareFields
---
Name: betterbuttonsconfig
---
BetterButtonsUtils:
  create:
    BetterButton_New: false
  edit:
    BetterButton_New: false
