---
Name: default
---
Database:
  host: default
  name: default
SilverStripe\View\SSViewer:
  theme: default
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - mysite/css/cms.css
  help_link: 'http://silverstripe.bigfork.co.uk/v3/'
