---
Name: 'default'
---
Database:
  host: 'default'
  name: 'default'
SSViewer:
  theme: 'default'
Page:
  extensions:
    - ShareCareFields
---
Name: 'focuspoint-connector'
Only:
  moduleexists: silverstripe-responsive-images
---
FocusPointImage:
  flush_on_change: true
---
Name: betterbuttonsconfig
---
BetterButtonsUtils:
  create:
    BetterButton_New: false
  edit:
    BetterButton_New: false
